name: Feature request
description: Request a new feature
body:
  - type: markdown
    attributes:
      value: |-
        Please join the [discord server](https://discord.gg/mYKK4BwGxe) for questions or ask them in [our discussions](https://github.com/BlockyDotJar/Tixte-Java-Library/discussions).
        
        Keep in mind that this isn't the place to learn Java.  
        Please head over to [StackOverflow](https://stackoverflow.com/questions/tagged/java) for your general programming questions.
  - type: checkboxes
    attributes:
      label: General troubleshooting
      description: You confirm to have made the following checks first.
      options:
        - label: I have checked for similar issues on the issue-tracker.
          required: true
        - label: I have updated to the [latest Tixte4J version](https://github.com/BlockyDotJar/JDA-Commons/releases/latest)
          required: true
        - label: I have checked the branches or the maintainer's prs for upcoming features.
          required: true
  - type: textarea
    attributes:
      label: "Feature request"
      description: "Provide a small description of the feature you want to have added."
      placeholder: "Tixte4J should get ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Example use-case"
      description: |-
        Provide some code or describe a possible use-case for this feature.
        
        The provided text will be rendered as Java code, so you don't have to provide a code block for it.
      placeholder: "public void newAwesomeMethod() { }"
      render: Java
